name: eawag
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - imageio
  - scikit-image  
  - pandas
  - matplotlib
  - seaborn
  - statsmodels
  - dask-core
  - dask-image  
  - zarr
  - numcodecs
  - jupyterlab
  - dask-labextension
  - matplotlib-scalebar
  - xlrd
  - openpyxl
  - tqdm
  - k3d