name: eawag
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - dask
  - dask-image
  - imageio
  - jupyterlab
  - ipywidgets   
  - numpy
  - pandas  
  - scikit-image
  - scipy    
  - matplotlib
  - matplotlib-scalebar
  - seaborn
  - tqdm
  - xlrd
  - openpyxl
  - k3d
  - pip:
    - ipywidgets==7.7.1
    - jupyterlab-widgets==1.1.0
    - widgetsnbextension==3.6.1  
